@baseUrl = http://localhost:3000

### create baggage data
POST {{baseUrl}}/baggages
// yo baggages chai handlers ko index ko line no .6 bala aako xa
Content-Type: application/json  
// application/json means data goes in json formatff 

{
    "name":"HARI"
}

### Get All baggages
GET {{baseUrl}}/baggages

### Get a specific baggage
GET {{baseUrl}}/baggages/6a09b4d24df9df8bc619ccb1


### Update s specific baggage
PATCH {{baseUrl}}/baggages/
Content-Type: application/json

{
    "name": "shockd",
    "completed": "true"
}

### delete a specific baggage
DELETE {{baseUrl}}/baggages/6a0ac37edbc05753380801c3




### create users 
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "deleteuser",
    "email": "delete1@email.com",
    "password":"abcdefgherdelete"
}

### getall users
GET {{baseUrl}}/users



### get a user
GET {{baseUrl}}/users/6a16780c627e312d1264237c


### update a user by id
PATCH {{baseUrl}}/users/6a16780c627e312d1264237c
Content-Type: application/json

{
    "email": "gita3@gmail.com"
}

### delete a user
DELETE {{baseUrl}}/users/6a16da93b9c120630d95a969



