@baseUrl = http://localhost:3000

@tripId=6a5350fe7f1d52efdc37767a

@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTNlNTMxNDM0YzRhMzM5NmQwN2UzN2EiLCJpYXQiOjE3ODQwMTU4MTAsImV4cCI6MTc4NDEwMjIxMH0.z8mCj0LN_lYcBTeTV4P46FrTWheFmwMLQPojJMEKSfw

@invitationToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTNlNTMxNDM0YzRhMzM5NmQwN2UzN2EiLCJpYXQiOjE3ODQwMTU4MTAsImV4cCI6MTc4NDEwMjIxMH0.z8mCj0LN_lYcBTeTV4P46FrTWheFmwMLQPojJMEKSfw





### create baggage data
POST {{baseUrl}}/baggages
// yo baggages chai handlers ko index ko line no .6 bala aako xa
Content-Type: application/json  
// application/json means data goes in json formatff 
Authorization: Bearer {{token}}

{
    "name":"HARI"
}

### Get All baggages
GET {{baseUrl}}/baggages
Content-Type: application/json
Authorization: Bearer {{token}}

### Get a specific baggage
GET {{baseUrl}}/baggages/6a09b4d24df9df8bc619ccb1
Content-Type: application/json
Authorization: Bearer {{token}}


### Update s specific baggage
PATCH {{baseUrl}}/baggages/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "shockd",
    "completed": "true"
}

### delete a specific baggage
DELETE {{baseUrl}}/baggages/6a0ac37edbc05753380801c3
Content-Type: application/json
Authorization: Bearer {{token}}




### create users 
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "deleteuser",
    "email": "delete1@email.com",
    "password":"abcdefgherdelete",
    "confirmPassword":""
}

### getall users
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}



### get a user
GET {{baseUrl}}/users/6a16780c627e312d1264237c
Content-Type: application/json
Authorization: Bearer {{token}}


### update a user by id
PATCH {{baseUrl}}/users/6a16780c627e312d1264237c
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "gita3@gmail.com"
}

### delete a user
DELETE {{baseUrl}}/users/6a16da93b9c120630d95a969
Content-Type: application/json
Authorization: Bearer {{token}}


### create a trip
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"TRIP TO THE HELL",
    "description":"summmer holiday",
    "startDate":"2026-12-15",
    "endDate":"2027-01-15",
     "destinations": ["mustang","dang","muktinath"],
    "budget":{
        "total": 1000
    }
}

### get all trips
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

### get a specific trip
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

### update a specific trip
PATCH {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "expenses": [
        {
            "name": "taxi",
            "amount": "600",
        }
    ]
}

### delete a specific trip
DELETE {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

### register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json


{
    "name": "sima says",
    "email": "sima12345825@gamil.com",
    "password": "sila563@3"
}


### login for user
POST {{baseUrl}}/auth/login
Content-Type: application/json


{
    "email": "sila12345825@gamil.com",
    "password": "sila563@3"
}

### send trip invitation 
POST {{baseUrl}}/trips/{{tripId}}/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "collaboratorEmails": [
        "dass2005nd@gmail.com"
    ]
}

### Accept invite
GET {{baseUrl}}/tripId/invite/accept?token={{invitationToken}}
Authorization: Bearer {{token}}






